# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows workflow to be triggered manually via the GitHub API, CLI or browser interface
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "simple"
  simple:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo "${{ secrets.PASSWORD }}"

  create-output:
    runs-on: self-hosted
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
    - id: step1
      run: echo "test=hello" >> $GITHUB_OUTPUT
  use-output:
    runs-on: self-hosted
    needs: create-output
    strategy: 
      matrix:
        number: [1,2,3,4,5,6,7,8,9,10]
    steps:
    - run: echo ${{needs.create-output.outputs.output1}} - ${{ matrix.number }}