on: 
  push:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: SloaneTribble/composite-workflow@v1
        with:
        # passing an input to composite-workflow@v1
          who-to-greet: 'Mona the Octocat'

      # using output from step with id "foo";
      # the action we call populates an input with name "random-number"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
  
  run_self_hosted:
    uses: ./.github/workflows/getting-started.yml
        
